# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f7ea3274660e3cb8cd8040926b727c953d87ac03b1b37a7e381d6054b232d2764f05a697b89f7064b350b318460f05458ea4dc82af0fe2d5b744b88ae16812

test:
  secret_key_base: 7b7e0627bd7c56365964e0fb77a9c2c434648a77a1648a3643fce10cacbf25c048b512c569bd63c3f107311ca5fbab81e88ddbe9b10cfed9923e49df96d2cdea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
